data: resources
output: results

dependency_graph:
    rulegraph: dependency_rulegraph.svg
    dag: dependency_dag.svg

# intermediate file locations
processed_data: results/processed_data
models: results/models
evaluation: results/evaluation

methods:
  - DeepCirCode
  - circDeep
  - SVM
  - RandomForest
