data: resources
output: results

dependency_graph:
  rulegraph: dependency_rulegraph.svg
  dag: dependency_dag.svg

# intermediate file locations
processed_data: results/processed_data
models: results/models
evaluation: results/evaluation
dev: True

# Global parameters
assembly: hg38

gene_annotations:
  hg19:
    chr_prefix: chr
    url: http://ftp.ensembl.org/pub/grch37/current/gtf/homo_sapiens/Homo_sapiens.GRCh37.87.chr.gtf.gz
    transcript_column: transcript_id
  hg38:
    chr_prefix: ''
    url: ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_38/gencode.v38.annotation.gtf.gz
#    ftp.ensembl.org/pub/release-104/gtf/homo_sapiens/Homo_sapiens.GRCh38.104.chr.gtf.gz
    transcript_column: transcript_id
    gene_column: gene_id

methods:
  JEDI:
    kmer_len: 3
    flank_len: 4
    epochs: 100
